### Upload avatar
PUT http://localhost:9080/car-manager/api/avatars/66fa581f-a118-45d1-83b3-b4ea0a5ad679
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar";
Content-Type: image/png

< ./avatars/avatar1.png
--boundary--

### Get avatar
GET http://localhost:9080/car-manager/api/avatars/66fa581f-a118-45d1-83b3-b4ea0a5ad679

### Delete avatar
DELETE http://localhost:9080/car-manager/api/avatars/8322d639-85db-483a-a772-03241c2fb173
