### Get all cars
GET http://localhost:9080/car-manager/api/cars
Accept: application/json

### Get car
GET http://localhost:9080/car-manager/api/cars/92aafd27-a3a8-417e-a769-7912738983ce
Accept: application/json

### Get cars by model
GET http://localhost:9080/car-manager/api/cars?modelId=ca28bdd7-76e9-4dc5-af56-f27f79f3f547
Accept: application/json

### Get cars by owner
GET http://localhost:9080/car-manager/api/cars?ownerId=97996278-5d91-4b61-a648-bb46976e0b05
Accept: application/json

### Create car
POST http://localhost:9080/car-manager/api/cars
Content-Type: application/json

{
  "model": {
    "id": "2aa24be3-d163-42f1-8907-f81f126efc92"
  },
  "owner": {
    "id": "a8df7e9f-ca66-4441-9a41-c770489771d9"
  },
  "licensePlate": "GDA55556",
  "mileage": 15000,
  "purchaseDate": "2023-06-15"
}

### Update car
PUT http://localhost:9080/car-manager/api/cars/4adcd689-a138-4dfe-b88e-8c625a3dff86
Content-Type: application/json

{
  "model": {
    "id": "2aa24be3-d163-42f1-8907-f81f126efc92"
  },
  "owner": {
    "id": "a8df7e9f-ca66-4441-9a41-c770489771d9"
  },
  "licensePlate": "GD12345",
  "mileage": 60000,
  "purchaseDate": "2025-05-15"
}

### Delete car
DELETE http://localhost:9080/car-manager/api/cars/9aeefe27-b89f-4738-b443-4de3952a7239