### Get all cars
GET http://localhost:9080/car-manager/api/jaxrs/cars
Accept: application/json

### Get all cars of specific model
GET http://localhost:9080/car-manager/api/jaxrs/models/0b86a240-75e5-40c8-aaea-7b86f9bfe3f6
Accept: application/json

### Get car info
GET http://localhost:9080/car-manager/api/jaxrs/models/ec6d51ac-87c5-491a-ac14-1c5ac85671d3/cars/1a743509-51de-49cb-9d8e-94801eac099d
Accept: application/json

### Create car
POST http://localhost:9080/car-manager/api/jaxrs/models/f485078b-5a97-46e0-85a5-0337e22c8918/cars
Content-Type: application/json

{
  "owner": {
    "id": "30f823c9-ac39-4c88-8b6b-08657579dbc0"
  },
  "licensePlate": "GDA-98333",
  "mileage": 25000,
  "purchaseDate": "2025-03-20"
}

### Update car
PUT http://localhost:9080/car-manager/api/jaxrs/models/83346664-268b-4732-b845-dc65b07c5c20/cars/cc80103a-94b2-4d01-b8a5-d8ac6dcfa133
Content-Type: application/json

{
  "licensePlate": "GDA-98765",
  "mileage": 75000,
  "purchaseDate": "2025-06-15"
}

### Delete car
DELETE http://localhost:9080/car-manager/api/jaxrs/models/c37f9173-dd72-42d3-834b-37f18fe603e7/cars/a0df494a-c4b7-45e5-8099-9f220a8d770b