### Get all models
GET http://localhost:9080/car-manager/api/jaxrs/models
Accept: application/json

### Get model info
GET http://localhost:9080/car-manager/api/jaxrs/models/0b86a240-75e5-40c8-aaea-7b86f9bfe3f6
Accept: application/json

### Create new model
POST http://localhost:9080/car-manager/api/jaxrs/models
Content-Type: application/json

{
  "brand": "AUDI",
  "name": "A4",
  "hp": 190
}

### Update model
PUT http://localhost:9080/car-manager/api/jaxrs/models/6c426d63-fa2a-4929-9b8a-907d587a2018
Content-Type: application/json

{
  "brand": "TOYOTA",
  "name": "Corolla v2",
  "hp": 170
}

### Delete model
DELETE http://localhost:9080/car-manager/api/jaxrs/models/fadd04a7-9dc3-433a-bad7-09s01b12ac65a